@startuml architecture-overview
top to bottom direction

'skinparam componentStyle rectangle
skinparam nodesep 100
skinparam ranksep 80
' node "Recommendation System" as recommendation_system {
'     [Attractions recommender]
'     [Show recommender]
'     [Restaurant recommender]
'     [Shop recommender]
' }

[Recommendation System] as recommendation_system
[Visitors Manager] as vm
[Planner] as planner
[Map manager] as map_manager
[Virtual Queueing System] as vqs

'actor Guest as guest

planner ..> map_manager : uses
recommendation_system ..> map_manager : uses
vqs <.. planner : uses
vqs <.. recommendation_system : uses
vm <.left. recommendation_system : uses
vm <.right. planner : uses
' guest <--> vqs : interact with
' guest .. map_manager : interacts with
' guest .. recommendation_system
' guest .. planner

@enduml