@startuml planner
left to right direction

component "Planner" as planner {
    component "Itinerary Service" as itinerary
}

component "Virtual Queuing System" as vqs
component "Map Manager" as mm
component "Visitor Manager" as vm

actor "Visitor" as visitor

itinerary <.up. vqs
itinerary <.up. mm
vm <.. itinerary

itinerary .. visitor

@enduml