@startuml recommender
left to right direction

component "Map Manager" as map_manager
component "Virtual Queing System" as virtual_queing
component "Visitor Manager" as visitor_manager

component "Recommendation System" {
    left to right direction
    component "Notifier Manager" as notifier_manager
    component "Attractions recommender" as attractions_recommender
    component "Shows recommender" as shows_recommender
    component "Reward Manager" as reward_manager
}

actor "Visitor" as visitor

attractions_recommender .up.> virtual_queing

visitor_manager <.down. attractions_recommender
shows_recommender .down.> visitor_manager

attractions_recommender .up.> map_manager
shows_recommender .up.> map_manager

reward_manager -- attractions_recommender
reward_manager -- shows_recommender

attractions_recommender -- notifier_manager
shows_recommender -- notifier_manager

notifier_manager .. visitor

@enduml