baseURL = 'https://icps-microcity.github.io/amusement-park-analysis/'
languageCode = 'en-us'
title = 'Amusement Park Analysis'
theme = "reveal-hugo"

[params.reveal_hugo]
theme = "white"
highlight_theme = "solarized-light"
width = "1440"
height = "900"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
